# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI

on: 
  workflow_call:
    inputs:
      pythonVersion:
        description: The Python version to install
        default: "3.10"
        required: false
        type: string
      pythonRequirements:
        description: Newline seperated list of requirements files
        default: |
          requirements.txt
          requirements.dev.txt
        required: false
        type: string
      banditPath:
        description: The space seperated paths and files to run bandit on
        required: true
        type: string
      banditContinueOnError:
        description: Continue workflow even on bandit error
        required: false
        type: boolean
        default: false

permissions:
  contents: read


jobs:
  static-analysis:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ inputs.pythonVersion }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.pythonVersion }}
        cache-dependency-path: ${{ inputs.pythonRequirements }}
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements.dev.txt

    - name: create tmp log directory
      run: mkdir /tmp/ci

    # static analysis check
    - name: bandit static analysis
      run: |
        bandit -r ${{ inputs.banditPath }}  
        bandit -r ${{ inputs.banditPath }} --format csv --output /tmp/ci/bandit.txt  
      continue-on-error: ${{ inputs.banditContinueOnError }}
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: bandit report
        path: /tmp/ci/bandit.txt
      
  sbom:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ inputs.pythonVersion }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.pythonVersion }}
        cache-dependency-path: ${{ inputs.pythonRequirements }}
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements.dev.txt

    - name: create tmp log directory
      run: mkdir /tmp/ci

    - name: install syft
      run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
    
    - name: run syft 
      run: syft $Python_ROOT_DIR/lib/python${{ inputs.pythonVersion }}/site-packages --file /tmp/ci/sbom.txt
    - uses: actions/upload-artifact@v3
      with:
        name: syft sBOM
        path: /tmp/ci/sbom.txt
