# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI

on: 
  workflow_call:
    inputs:
      pythonVersion:
        description: The Python version to install
        default: "3.10"
        required: false
        type: string
      pythonRequirements:
        description: Newline seperated list of requirements files
        default: |
          requirements.txt
          requirements.dev.txt
        required: false
        type: string
      pytestPath:
        description: The path to point pytest to
        default: tests
        required: false
        type: string
      coveragePath:
        description: The path to point pytest-cov to
        required: false
        type: string 
        default: "."
      runIntegrationTests:
        description: Run integration tests if true
        required: true
        type: boolean

permissions:
  contents: read


jobs:
  unit-testing:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ inputs.pythonVersion }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.pythonVersion }}
        cache-dependency-path: ${{ inputs.pythonRequirements }}
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements.dev.txt

    - name: unit tests
      run: pytest ${{ inputs.pytestPath }} -m "not integration" -v --cov=${{ inputs.coveragePath }} --cov-report=term

  integration-testing:
    runs-on: ubuntu-22.04
    if: ${{ inputs.runIntegrationTests }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ inputs.pythonVersion }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.pythonVersion }}
        cache-dependency-path: ${{ inputs.pythonRequirements }}
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements.dev.txt

    - name: unit tests
      run: pytest ${{ inputs.pytestPath }} -m "integration" -v 